<script>
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("Whoops!")), 1000);
});
// .catch(f) is the same as promise.then(null, f)

promise.catch(alert); // shows "Error: Whoops!" after 1 second
//The call .catch(f) is a complete analog of .then(null, f), it’s just a shorthand.
</script>